using System;
using Cipa.Domain.Entities;
using Cipa.Domain.Helpers;
using Microsoft.EntityFrameworkCore;

namespace Cipa.Infra.Data.Context
{
    public static class ModelBuilderExtensions
    {
        public static void Seed(this ModelBuilder modelBuilder)
        {
            Conta conta = new Conta
            {
                Id = 1,
                Ativa = true,
                DataInicio = new DateTime(2019, 1, 1),
                DataFim = new DateTime(2020, 12, 31),
                PlanoId = null,
                QtdaEstabelecimentos = 2,
                DataCadastro = new DateTime(2019, 1, 1)
            };

            Grupo[] grupos = new Grupo[45] {
                new Grupo { CodigoGrupo = "C-1", Id = 1 },
                new Grupo { CodigoGrupo = "C-1a", Id = 2 },
                new Grupo { CodigoGrupo = "C-2", Id = 3 },
                new Grupo { CodigoGrupo = "C-3", Id = 4 },
                new Grupo { CodigoGrupo = "C-3a", Id = 5 },
                new Grupo { CodigoGrupo = "C-4", Id = 6 },
                new Grupo { CodigoGrupo = "C-5", Id = 7 },
                new Grupo { CodigoGrupo = "C-5a", Id = 8 },
                new Grupo { CodigoGrupo = "C-6", Id = 9 },
                new Grupo { CodigoGrupo = "C-7", Id = 10 },
                new Grupo { CodigoGrupo = "C-7a", Id = 11 },
                new Grupo { CodigoGrupo = "C-8", Id = 12 },
                new Grupo { CodigoGrupo = "C-9", Id = 13 },
                new Grupo { CodigoGrupo = "C-10", Id = 14 },
                new Grupo { CodigoGrupo = "C-11", Id = 15 },
                new Grupo { CodigoGrupo = "C-12", Id = 16 },
                new Grupo { CodigoGrupo = "C-13", Id = 17 },
                new Grupo { CodigoGrupo = "C-14", Id = 18 },
                new Grupo { CodigoGrupo = "C-14a", Id = 19 },
                new Grupo { CodigoGrupo = "C-15", Id = 20 },
                new Grupo { CodigoGrupo = "C-16", Id = 21 },
                new Grupo { CodigoGrupo = "C-17", Id = 22 },
                new Grupo { CodigoGrupo = "C-18", Id = 23 },
                new Grupo { CodigoGrupo = "C-18a", Id = 24 },
                new Grupo { CodigoGrupo = "C-19", Id = 25 },
                new Grupo { CodigoGrupo = "C-20", Id = 26 },
                new Grupo { CodigoGrupo = "C-21", Id = 27 },
                new Grupo { CodigoGrupo = "C-22", Id = 28 },
                new Grupo { CodigoGrupo = "C-23", Id = 29 },
                new Grupo { CodigoGrupo = "C-24", Id = 30 },
                new Grupo { CodigoGrupo = "C-24a", Id = 31 },
                new Grupo { CodigoGrupo = "C-24b", Id = 32 },
                new Grupo { CodigoGrupo = "C-24c", Id = 33 },
                new Grupo { CodigoGrupo = "C-24d", Id = 34 },
                new Grupo { CodigoGrupo = "C-25", Id = 35 },
                new Grupo { CodigoGrupo = "C-26", Id = 36 },
                new Grupo { CodigoGrupo = "C-27", Id = 37 },
                new Grupo { CodigoGrupo = "C-28", Id = 38 },
                new Grupo { CodigoGrupo = "C-29", Id = 39 },
                new Grupo { CodigoGrupo = "C-30", Id = 40 },
                new Grupo { CodigoGrupo = "C-31", Id = 41 },
                new Grupo { CodigoGrupo = "C-32", Id = 42 },
                new Grupo { CodigoGrupo = "C-33", Id = 43 },
                new Grupo { CodigoGrupo = "C-34", Id = 44 },
                new Grupo { CodigoGrupo = "C-35", Id = 45 }
            };

            LimiteDimensionamento[] limitesDimensionamentos = new LimiteDimensionamento[45] {
                new LimiteDimensionamento { Id = 1, Limite = 10000, IntervaloAcrescimo = 2500, AcrescimoEfetivos = 2,  AcrescimoSuplentes = 2 },
                new LimiteDimensionamento { Id = 2, Limite = 10000, IntervaloAcrescimo = 2500, AcrescimoEfetivos = 2,  AcrescimoSuplentes = 2 },
                new LimiteDimensionamento { Id = 3, Limite = 10000, IntervaloAcrescimo = 2500, AcrescimoEfetivos = 2,  AcrescimoSuplentes = 1 },
                new LimiteDimensionamento { Id = 4, Limite = 10000, IntervaloAcrescimo = 2500, AcrescimoEfetivos = 2,  AcrescimoSuplentes = 2 },
                new LimiteDimensionamento { Id = 5, Limite = 10000, IntervaloAcrescimo = 2500, AcrescimoEfetivos = 1,  AcrescimoSuplentes = 1 },
                new LimiteDimensionamento { Id = 6, Limite = 10000, IntervaloAcrescimo = 2500, AcrescimoEfetivos = 1,  AcrescimoSuplentes = 1 },
                new LimiteDimensionamento { Id = 7, Limite = 10000, IntervaloAcrescimo = 2500, AcrescimoEfetivos = 2,  AcrescimoSuplentes = 2 },
                new LimiteDimensionamento { Id = 8, Limite = 10000, IntervaloAcrescimo = 2500, AcrescimoEfetivos = 1,  AcrescimoSuplentes = 1 },
                new LimiteDimensionamento { Id = 9, Limite = 10000, IntervaloAcrescimo = 2500, AcrescimoEfetivos = 2,  AcrescimoSuplentes = 2 },
                new LimiteDimensionamento { Id = 10, Limite = 10000, IntervaloAcrescimo = 2500, AcrescimoEfetivos = 1,  AcrescimoSuplentes = 1 },
                new LimiteDimensionamento { Id = 11, Limite = 10000, IntervaloAcrescimo = 2500, AcrescimoEfetivos = 2,  AcrescimoSuplentes = 2 },
                new LimiteDimensionamento { Id = 12, Limite = 10000, IntervaloAcrescimo = 2500, AcrescimoEfetivos = 1,  AcrescimoSuplentes = 1 },
                new LimiteDimensionamento { Id = 13, Limite = 10000, IntervaloAcrescimo = 2500, AcrescimoEfetivos = 1,  AcrescimoSuplentes = 1 },
                new LimiteDimensionamento { Id = 14, Limite = 10000, IntervaloAcrescimo = 2500, AcrescimoEfetivos = 2,  AcrescimoSuplentes = 2 },
                new LimiteDimensionamento { Id = 15, Limite = 10000, IntervaloAcrescimo = 2500, AcrescimoEfetivos = 2,  AcrescimoSuplentes = 2 },
                new LimiteDimensionamento { Id = 16, Limite = 10000, IntervaloAcrescimo = 2500, AcrescimoEfetivos = 2,  AcrescimoSuplentes = 2 },
                new LimiteDimensionamento { Id = 17, Limite = 10000, IntervaloAcrescimo = 2500, AcrescimoEfetivos = 2,  AcrescimoSuplentes = 2 },
                new LimiteDimensionamento { Id = 18, Limite = 10000, IntervaloAcrescimo = 2500, AcrescimoEfetivos = 2,  AcrescimoSuplentes = 2 },
                new LimiteDimensionamento { Id = 19, Limite = 10000, IntervaloAcrescimo = 2500, AcrescimoEfetivos = 1,  AcrescimoSuplentes = 1 },
                new LimiteDimensionamento { Id = 20, Limite = 10000, IntervaloAcrescimo = 2500, AcrescimoEfetivos = 2,  AcrescimoSuplentes = 2 },
                new LimiteDimensionamento { Id = 21, Limite = 10000, IntervaloAcrescimo = 2500, AcrescimoEfetivos = 2,  AcrescimoSuplentes = 2 },
                new LimiteDimensionamento { Id = 22, Limite = 10000, IntervaloAcrescimo = 2500, AcrescimoEfetivos = 2,  AcrescimoSuplentes = 2 },
                new LimiteDimensionamento { Id = 23, Limite = 10000, IntervaloAcrescimo = 2500, AcrescimoEfetivos = 2,  AcrescimoSuplentes = 2 },
                new LimiteDimensionamento { Id = 24, Limite = 10000, IntervaloAcrescimo = 2500, AcrescimoEfetivos = 2,  AcrescimoSuplentes = 2 },
                new LimiteDimensionamento { Id = 25, Limite = 10000, IntervaloAcrescimo = 2500, AcrescimoEfetivos = 1,  AcrescimoSuplentes = 1 },
                new LimiteDimensionamento { Id = 26, Limite = 10000, IntervaloAcrescimo = 2500, AcrescimoEfetivos = 2,  AcrescimoSuplentes = 1 },
                new LimiteDimensionamento { Id = 27, Limite = 10000, IntervaloAcrescimo = 2500, AcrescimoEfetivos = 1,  AcrescimoSuplentes = 1 },
                new LimiteDimensionamento { Id = 28, Limite = 10000, IntervaloAcrescimo = 2500, AcrescimoEfetivos = 2,  AcrescimoSuplentes = 2 },
                new LimiteDimensionamento { Id = 29, Limite = 10000, IntervaloAcrescimo = 2500, AcrescimoEfetivos = 1,  AcrescimoSuplentes = 1 },
                new LimiteDimensionamento { Id = 30, Limite = 10000, IntervaloAcrescimo = 2500, AcrescimoEfetivos = 2,  AcrescimoSuplentes = 2 },
                new LimiteDimensionamento { Id = 31, Limite = 10000, IntervaloAcrescimo = 2500, AcrescimoEfetivos = 1,  AcrescimoSuplentes = 1 },
                new LimiteDimensionamento { Id = 32, Limite = 10000, IntervaloAcrescimo = 2500, AcrescimoEfetivos = 2,  AcrescimoSuplentes = 2 },
                new LimiteDimensionamento { Id = 33, Limite = 10000, IntervaloAcrescimo = 2500, AcrescimoEfetivos = 1,  AcrescimoSuplentes = 1 },
                new LimiteDimensionamento { Id = 34, Limite = 10000, IntervaloAcrescimo = 2500, AcrescimoEfetivos = 1,  AcrescimoSuplentes = 1 },
                new LimiteDimensionamento { Id = 35, Limite = 10000, IntervaloAcrescimo = 2500, AcrescimoEfetivos = 1,  AcrescimoSuplentes = 1 },
                new LimiteDimensionamento { Id = 36, Limite = 10000, IntervaloAcrescimo = 2500, AcrescimoEfetivos = 1,  AcrescimoSuplentes = 1 },
                new LimiteDimensionamento { Id = 37, Limite = 10000, IntervaloAcrescimo = 2500, AcrescimoEfetivos = 1,  AcrescimoSuplentes = 1 },
                new LimiteDimensionamento { Id = 38, Limite = 10000, IntervaloAcrescimo = 2500, AcrescimoEfetivos = 1,  AcrescimoSuplentes = 1 },
                new LimiteDimensionamento { Id = 39, Limite = 10000, IntervaloAcrescimo = 2500, AcrescimoEfetivos = 1,  AcrescimoSuplentes = 1 },
                new LimiteDimensionamento { Id = 40, Limite = 10000, IntervaloAcrescimo = 2500, AcrescimoEfetivos = 2,  AcrescimoSuplentes = 1 },
                new LimiteDimensionamento { Id = 41, Limite = 10000, IntervaloAcrescimo = 2500, AcrescimoEfetivos = 1,  AcrescimoSuplentes = 1 },
                new LimiteDimensionamento { Id = 42, Limite = 10000, IntervaloAcrescimo = 2500, AcrescimoEfetivos = 1,  AcrescimoSuplentes = 1 },
                new LimiteDimensionamento { Id = 43, Limite = 10000, IntervaloAcrescimo = 2500, AcrescimoEfetivos = 1,  AcrescimoSuplentes = 1 },
                new LimiteDimensionamento { Id = 44, Limite = 10000, IntervaloAcrescimo = 2500, AcrescimoEfetivos = 2,  AcrescimoSuplentes = 2 },
                new LimiteDimensionamento { Id = 45, Limite = 10000, IntervaloAcrescimo = 2500, AcrescimoEfetivos = 1,  AcrescimoSuplentes = 1 }
            };

            LinhaDimensionamento[] linhaDimensionamentos = new LinhaDimensionamento[366] {
                new LinhaDimensionamento { Id = 1, GrupoId = 1, Minimo = 0, Maximo = 19, QtdaEfetivos = 0, QtdaSuplentes = 0 },
                new LinhaDimensionamento { Id = 2, GrupoId = 1, Minimo = 20, Maximo = 50, QtdaEfetivos = 1, QtdaSuplentes = 1 },
                new LinhaDimensionamento { Id = 3, GrupoId = 1, Minimo = 51, Maximo = 100, QtdaEfetivos = 3, QtdaSuplentes = 3 },
                new LinhaDimensionamento { Id = 4, GrupoId = 1, Minimo = 101, Maximo = 500, QtdaEfetivos = 4, QtdaSuplentes = 3 },
                new LinhaDimensionamento { Id = 5, GrupoId = 1, Minimo = 501, Maximo = 1000, QtdaEfetivos = 6, QtdaSuplentes = 4 },
                new LinhaDimensionamento { Id = 6, GrupoId = 1, Minimo = 1001, Maximo = 2500, QtdaEfetivos = 9, QtdaSuplentes = 7 },
                new LinhaDimensionamento { Id = 7, GrupoId = 1, Minimo = 2501, Maximo = 5000, QtdaEfetivos = 12, QtdaSuplentes = 9 },
                new LinhaDimensionamento { Id = 8, GrupoId = 1, Minimo = 5001, Maximo = 10000, QtdaEfetivos = 15, QtdaSuplentes = 12 },
                new LinhaDimensionamento { Id = 9, GrupoId = 2, Minimo = 0, Maximo = 19, QtdaEfetivos = 0, QtdaSuplentes = 0 },
                new LinhaDimensionamento { Id = 10, GrupoId = 2, Minimo = 20, Maximo = 50, QtdaEfetivos = 1, QtdaSuplentes = 1 },
                new LinhaDimensionamento { Id = 11, GrupoId = 2, Minimo = 51, Maximo = 100, QtdaEfetivos = 3, QtdaSuplentes = 3 },
                new LinhaDimensionamento { Id = 12, GrupoId = 2, Minimo = 101, Maximo = 300, QtdaEfetivos = 4, QtdaSuplentes = 3 },
                new LinhaDimensionamento { Id = 13, GrupoId = 2, Minimo = 301, Maximo = 500, QtdaEfetivos = 4, QtdaSuplentes = 4 },
                new LinhaDimensionamento { Id = 14, GrupoId = 2, Minimo = 501, Maximo = 1000, QtdaEfetivos = 6, QtdaSuplentes = 5 },
                new LinhaDimensionamento { Id = 15, GrupoId = 2, Minimo = 1001, Maximo = 2500, QtdaEfetivos = 9, QtdaSuplentes = 8 },
                new LinhaDimensionamento { Id = 16, GrupoId = 2, Minimo = 2501, Maximo = 5000, QtdaEfetivos = 12, QtdaSuplentes = 9 },
                new LinhaDimensionamento { Id = 17, GrupoId = 2, Minimo = 5001, Maximo = 10000, QtdaEfetivos = 15, QtdaSuplentes = 12 },
                new LinhaDimensionamento { Id = 18, GrupoId = 3, Minimo = 0, Maximo = 19, QtdaEfetivos = 0, QtdaSuplentes = 0 },
                new LinhaDimensionamento { Id = 19, GrupoId = 3, Minimo = 20, Maximo = 50, QtdaEfetivos = 1, QtdaSuplentes = 1 },
                new LinhaDimensionamento { Id = 20, GrupoId = 3, Minimo = 51, Maximo = 100, QtdaEfetivos = 2, QtdaSuplentes = 2 },
                new LinhaDimensionamento { Id = 21, GrupoId = 3, Minimo = 101, Maximo = 120, QtdaEfetivos = 3, QtdaSuplentes = 3 },
                new LinhaDimensionamento { Id = 22, GrupoId = 3, Minimo = 121, Maximo = 140, QtdaEfetivos = 4, QtdaSuplentes = 3 },
                new LinhaDimensionamento { Id = 23, GrupoId = 3, Minimo = 141, Maximo = 300, QtdaEfetivos = 4, QtdaSuplentes = 4 },
                new LinhaDimensionamento { Id = 24, GrupoId = 3, Minimo = 301, Maximo = 500, QtdaEfetivos = 5, QtdaSuplentes = 4 },
                new LinhaDimensionamento { Id = 25, GrupoId = 3, Minimo = 501, Maximo = 1000, QtdaEfetivos = 6, QtdaSuplentes = 5 },
                new LinhaDimensionamento { Id = 26, GrupoId = 3, Minimo = 1001, Maximo = 2500, QtdaEfetivos = 7, QtdaSuplentes = 6 },
                new LinhaDimensionamento { Id = 27, GrupoId = 3, Minimo = 2501, Maximo = 5000, QtdaEfetivos = 10, QtdaSuplentes = 7 },
                new LinhaDimensionamento { Id = 28, GrupoId = 3, Minimo = 5001, Maximo = 10000, QtdaEfetivos = 11, QtdaSuplentes = 9 },
                new LinhaDimensionamento { Id = 29, GrupoId = 4, Minimo = 0, Maximo = 19, QtdaEfetivos = 0, QtdaSuplentes = 0 },
                new LinhaDimensionamento { Id = 30, GrupoId = 4, Minimo = 20, Maximo = 50, QtdaEfetivos = 1, QtdaSuplentes = 1 },
                new LinhaDimensionamento { Id = 31, GrupoId = 4, Minimo = 51, Maximo = 100, QtdaEfetivos = 2, QtdaSuplentes = 2 },
                new LinhaDimensionamento { Id = 32, GrupoId = 4, Minimo = 101, Maximo = 140, QtdaEfetivos = 3, QtdaSuplentes = 3 },
                new LinhaDimensionamento { Id = 33, GrupoId = 4, Minimo = 141, Maximo = 300, QtdaEfetivos = 4, QtdaSuplentes = 4 },
                new LinhaDimensionamento { Id = 34, GrupoId = 4, Minimo = 301, Maximo = 500, QtdaEfetivos = 5, QtdaSuplentes = 4 },
                new LinhaDimensionamento { Id = 35, GrupoId = 4, Minimo = 501, Maximo = 1000, QtdaEfetivos = 6, QtdaSuplentes = 5 },
                new LinhaDimensionamento { Id = 36, GrupoId = 4, Minimo = 1001, Maximo = 2500, QtdaEfetivos = 7, QtdaSuplentes = 6 },
                new LinhaDimensionamento { Id = 37, GrupoId = 4, Minimo = 2501, Maximo = 10000, QtdaEfetivos = 10, QtdaSuplentes = 8 },
                new LinhaDimensionamento { Id = 38, GrupoId = 5, Minimo = 0, Maximo = 50, QtdaEfetivos = 0, QtdaSuplentes = 0 },
                new LinhaDimensionamento { Id = 39, GrupoId = 5, Minimo = 51, Maximo = 100, QtdaEfetivos = 1, QtdaSuplentes = 1 },
                new LinhaDimensionamento { Id = 40, GrupoId = 5, Minimo = 101, Maximo = 300, QtdaEfetivos = 2, QtdaSuplentes = 2 },
                new LinhaDimensionamento { Id = 41, GrupoId = 5, Minimo = 301, Maximo = 1000, QtdaEfetivos = 3, QtdaSuplentes = 3 },
                new LinhaDimensionamento { Id = 42, GrupoId = 5, Minimo = 1001, Maximo = 2500, QtdaEfetivos = 4, QtdaSuplentes = 3 },
                new LinhaDimensionamento { Id = 43, GrupoId = 5, Minimo = 2501, Maximo = 5000, QtdaEfetivos = 5, QtdaSuplentes = 4 },
                new LinhaDimensionamento { Id = 44, GrupoId = 5, Minimo = 5001, Maximo = 10000, QtdaEfetivos = 6, QtdaSuplentes = 5 },
                new LinhaDimensionamento { Id = 45, GrupoId = 6, Minimo = 0, Maximo = 29, QtdaEfetivos = 0, QtdaSuplentes = 0 },
                new LinhaDimensionamento { Id = 46, GrupoId = 6, Minimo = 30, Maximo = 140, QtdaEfetivos = 1, QtdaSuplentes = 1 },
                new LinhaDimensionamento { Id = 47, GrupoId = 6, Minimo = 141, Maximo = 1000, QtdaEfetivos = 2, QtdaSuplentes = 2 },
                new LinhaDimensionamento { Id = 48, GrupoId = 6, Minimo = 1001, Maximo = 2500, QtdaEfetivos = 3, QtdaSuplentes = 3 },
                new LinhaDimensionamento { Id = 49, GrupoId = 6, Minimo = 2501, Maximo = 5000, QtdaEfetivos = 5, QtdaSuplentes = 4 },
                new LinhaDimensionamento { Id = 50, GrupoId = 6, Minimo = 5001, Maximo = 10000, QtdaEfetivos = 6, QtdaSuplentes = 4 },
                new LinhaDimensionamento { Id = 51, GrupoId = 7, Minimo = 0, Maximo = 19, QtdaEfetivos = 0, QtdaSuplentes = 0 },
                new LinhaDimensionamento { Id = 52, GrupoId = 7, Minimo = 20, Maximo = 50, QtdaEfetivos = 1, QtdaSuplentes = 1 },
                new LinhaDimensionamento { Id = 53, GrupoId = 7, Minimo = 51, Maximo = 80, QtdaEfetivos = 2, QtdaSuplentes = 2 },
                new LinhaDimensionamento { Id = 54, GrupoId = 7, Minimo = 81, Maximo = 120, QtdaEfetivos = 3, QtdaSuplentes = 3 },
                new LinhaDimensionamento { Id = 55, GrupoId = 7, Minimo = 121, Maximo = 140, QtdaEfetivos = 4, QtdaSuplentes = 3 },
                new LinhaDimensionamento { Id = 56, GrupoId = 7, Minimo = 141, Maximo = 500, QtdaEfetivos = 4, QtdaSuplentes = 4 },
                new LinhaDimensionamento { Id = 57, GrupoId = 7, Minimo = 501, Maximo = 1000, QtdaEfetivos = 6, QtdaSuplentes = 5 },
                new LinhaDimensionamento { Id = 58, GrupoId = 7, Minimo = 1001, Maximo = 5000, QtdaEfetivos = 9, QtdaSuplentes = 7 },
                new LinhaDimensionamento { Id = 59, GrupoId = 7, Minimo = 5001, Maximo = 10000, QtdaEfetivos = 11, QtdaSuplentes = 9 },
                new LinhaDimensionamento { Id = 60, GrupoId = 8, Minimo = 0, Maximo = 50, QtdaEfetivos = 0, QtdaSuplentes = 0 },
                new LinhaDimensionamento { Id = 61, GrupoId = 8, Minimo = 51, Maximo = 100, QtdaEfetivos = 1, QtdaSuplentes = 1 },
                new LinhaDimensionamento { Id = 62, GrupoId = 8, Minimo = 101, Maximo = 300, QtdaEfetivos = 2, QtdaSuplentes = 2 },
                new LinhaDimensionamento { Id = 63, GrupoId = 8, Minimo = 301, Maximo = 1000, QtdaEfetivos = 3, QtdaSuplentes = 3 },
                new LinhaDimensionamento { Id = 64, GrupoId = 8, Minimo = 1001, Maximo = 2500, QtdaEfetivos = 4, QtdaSuplentes = 3 },
                new LinhaDimensionamento { Id = 65, GrupoId = 8, Minimo = 2501, Maximo = 5000, QtdaEfetivos = 6, QtdaSuplentes = 4 },
                new LinhaDimensionamento { Id = 66, GrupoId = 8, Minimo = 5001, Maximo = 10000, QtdaEfetivos = 7, QtdaSuplentes = 5 },
                new LinhaDimensionamento { Id = 67, GrupoId = 9, Minimo = 0, Maximo = 19, QtdaEfetivos = 0, QtdaSuplentes = 0 },
                new LinhaDimensionamento { Id = 68, GrupoId = 9, Minimo = 20, Maximo = 50, QtdaEfetivos = 1, QtdaSuplentes = 1 },
                new LinhaDimensionamento { Id = 69, GrupoId = 9, Minimo = 51, Maximo = 80, QtdaEfetivos = 2, QtdaSuplentes = 2 },
                new LinhaDimensionamento { Id = 70, GrupoId = 9, Minimo = 81, Maximo = 120, QtdaEfetivos = 3, QtdaSuplentes = 3 },
                new LinhaDimensionamento { Id = 71, GrupoId = 9, Minimo = 121, Maximo = 140, QtdaEfetivos = 4, QtdaSuplentes = 3 },
                new LinhaDimensionamento { Id = 72, GrupoId = 9, Minimo = 141, Maximo = 500, QtdaEfetivos = 5, QtdaSuplentes = 4 },
                new LinhaDimensionamento { Id = 73, GrupoId = 9, Minimo = 501, Maximo = 1000, QtdaEfetivos = 6, QtdaSuplentes = 4 },
                new LinhaDimensionamento { Id = 74, GrupoId = 9, Minimo = 1001, Maximo = 2500, QtdaEfetivos = 8, QtdaSuplentes = 6 },
                new LinhaDimensionamento { Id = 75, GrupoId = 9, Minimo = 2501, Maximo = 5000, QtdaEfetivos = 10, QtdaSuplentes = 8 },
                new LinhaDimensionamento { Id = 76, GrupoId = 9, Minimo = 5001, Maximo = 10000, QtdaEfetivos = 12, QtdaSuplentes = 10 },
                new LinhaDimensionamento { Id = 77, GrupoId = 10, Minimo = 0, Maximo = 50, QtdaEfetivos = 0, QtdaSuplentes = 0 },
                new LinhaDimensionamento { Id = 78, GrupoId = 10, Minimo = 51, Maximo = 100, QtdaEfetivos = 1, QtdaSuplentes = 1 },
                new LinhaDimensionamento { Id = 79, GrupoId = 10, Minimo = 101, Maximo = 500, QtdaEfetivos = 2, QtdaSuplentes = 2 },
                new LinhaDimensionamento { Id = 80, GrupoId = 10, Minimo = 501, Maximo = 1000, QtdaEfetivos = 3, QtdaSuplentes = 3 },
                new LinhaDimensionamento { Id = 81, GrupoId = 10, Minimo = 1001, Maximo = 2500, QtdaEfetivos = 4, QtdaSuplentes = 3 },
                new LinhaDimensionamento { Id = 82, GrupoId = 10, Minimo = 2501, Maximo = 5000, QtdaEfetivos = 5, QtdaSuplentes = 4 },
                new LinhaDimensionamento { Id = 83, GrupoId = 10, Minimo = 5001, Maximo = 10000, QtdaEfetivos = 6, QtdaSuplentes = 4 },
                new LinhaDimensionamento { Id = 84, GrupoId = 11, Minimo = 0, Maximo = 19, QtdaEfetivos = 0, QtdaSuplentes = 0 },
                new LinhaDimensionamento { Id = 85, GrupoId = 11, Minimo = 20, Maximo = 50, QtdaEfetivos = 1, QtdaSuplentes = 1 },
                new LinhaDimensionamento { Id = 86, GrupoId = 11, Minimo = 51, Maximo = 100, QtdaEfetivos = 2, QtdaSuplentes = 2 },
                new LinhaDimensionamento { Id = 87, GrupoId = 11, Minimo = 101, Maximo = 140, QtdaEfetivos = 3, QtdaSuplentes = 3 },
                new LinhaDimensionamento { Id = 88, GrupoId = 11, Minimo = 141, Maximo = 300, QtdaEfetivos = 4, QtdaSuplentes = 3 },
                new LinhaDimensionamento { Id = 89, GrupoId = 11, Minimo = 301, Maximo = 500, QtdaEfetivos = 5, QtdaSuplentes = 4 },
                new LinhaDimensionamento { Id = 90, GrupoId = 11, Minimo = 501, Maximo = 1000, QtdaEfetivos = 6, QtdaSuplentes = 5 },
                new LinhaDimensionamento { Id = 91, GrupoId = 11, Minimo = 1001, Maximo = 2500, QtdaEfetivos = 8, QtdaSuplentes = 7 },
                new LinhaDimensionamento { Id = 92, GrupoId = 11, Minimo = 2501, Maximo = 5000, QtdaEfetivos = 9, QtdaSuplentes = 8 },
                new LinhaDimensionamento { Id = 93, GrupoId = 11, Minimo = 5001, Maximo = 10000, QtdaEfetivos = 10, QtdaSuplentes = 8 },
                new LinhaDimensionamento { Id = 94, GrupoId = 12, Minimo = 0, Maximo = 19, QtdaEfetivos = 0, QtdaSuplentes = 0 },
                new LinhaDimensionamento { Id = 95, GrupoId = 12, Minimo = 20, Maximo = 50, QtdaEfetivos = 1, QtdaSuplentes = 1 },
                new LinhaDimensionamento { Id = 96, GrupoId = 12, Minimo = 51, Maximo = 100, QtdaEfetivos = 2, QtdaSuplentes = 2 },
                new LinhaDimensionamento { Id = 97, GrupoId = 12, Minimo = 101, Maximo = 140, QtdaEfetivos = 3, QtdaSuplentes = 3 },
                new LinhaDimensionamento { Id = 98, GrupoId = 12, Minimo = 141, Maximo = 300, QtdaEfetivos = 4, QtdaSuplentes = 3 },
                new LinhaDimensionamento { Id = 99, GrupoId = 12, Minimo = 301, Maximo = 500, QtdaEfetivos = 5, QtdaSuplentes = 4 },
                new LinhaDimensionamento { Id = 100, GrupoId = 12, Minimo = 501, Maximo = 1000, QtdaEfetivos = 6, QtdaSuplentes = 4 },
                new LinhaDimensionamento { Id = 101, GrupoId = 12, Minimo = 1001, Maximo = 2500, QtdaEfetivos = 7, QtdaSuplentes = 5 },
                new LinhaDimensionamento { Id = 102, GrupoId = 12, Minimo = 2501, Maximo = 5000, QtdaEfetivos = 8, QtdaSuplentes = 6 },
                new LinhaDimensionamento { Id = 103, GrupoId = 12, Minimo = 5001, Maximo = 10000, QtdaEfetivos = 10, QtdaSuplentes = 8 },
                new LinhaDimensionamento { Id = 104, GrupoId = 13, Minimo = 0, Maximo = 50, QtdaEfetivos = 0, QtdaSuplentes = 0 },
                new LinhaDimensionamento { Id = 105, GrupoId = 13, Minimo = 51, Maximo = 120, QtdaEfetivos = 1, QtdaSuplentes = 1 },
                new LinhaDimensionamento { Id = 106, GrupoId = 13, Minimo = 121, Maximo = 500, QtdaEfetivos = 2, QtdaSuplentes = 2 },
                new LinhaDimensionamento { Id = 107, GrupoId = 13, Minimo = 501, Maximo = 1000, QtdaEfetivos = 3, QtdaSuplentes = 3 },
                new LinhaDimensionamento { Id = 108, GrupoId = 13, Minimo = 1001, Maximo = 2500, QtdaEfetivos = 5, QtdaSuplentes = 4 },
                new LinhaDimensionamento { Id = 109, GrupoId = 13, Minimo = 2501, Maximo = 5000, QtdaEfetivos = 6, QtdaSuplentes = 4 },
                new LinhaDimensionamento { Id = 110, GrupoId = 13, Minimo = 5001, Maximo = 10000, QtdaEfetivos = 7, QtdaSuplentes = 5 },
                new LinhaDimensionamento { Id = 111, GrupoId = 14, Minimo = 0, Maximo = 19, QtdaEfetivos = 0, QtdaSuplentes = 0 },
                new LinhaDimensionamento { Id = 112, GrupoId = 14, Minimo = 20, Maximo = 50, QtdaEfetivos = 1, QtdaSuplentes = 1 },
                new LinhaDimensionamento { Id = 113, GrupoId = 14, Minimo = 51, Maximo = 100, QtdaEfetivos = 2, QtdaSuplentes = 2 },
                new LinhaDimensionamento { Id = 114, GrupoId = 14, Minimo = 101, Maximo = 140, QtdaEfetivos = 3, QtdaSuplentes = 3 },
                new LinhaDimensionamento { Id = 115, GrupoId = 14, Minimo = 141, Maximo = 300, QtdaEfetivos = 4, QtdaSuplentes = 3 },
                new LinhaDimensionamento { Id = 116, GrupoId = 14, Minimo = 301, Maximo = 500, QtdaEfetivos = 4, QtdaSuplentes = 4 },
                new LinhaDimensionamento { Id = 117, GrupoId = 14, Minimo = 501, Maximo = 1000, QtdaEfetivos = 5, QtdaSuplentes = 4 },
                new LinhaDimensionamento { Id = 118, GrupoId = 14, Minimo = 1001, Maximo = 2500, QtdaEfetivos = 8, QtdaSuplentes = 6 },
                new LinhaDimensionamento { Id = 119, GrupoId = 14, Minimo = 2501, Maximo = 5000, QtdaEfetivos = 9, QtdaSuplentes = 7 },
                new LinhaDimensionamento { Id = 120, GrupoId = 14, Minimo = 5001, Maximo = 10000, QtdaEfetivos = 10, QtdaSuplentes = 8 },
                new LinhaDimensionamento { Id = 121, GrupoId = 15, Minimo = 0, Maximo = 19, QtdaEfetivos = 0, QtdaSuplentes = 0 },
                new LinhaDimensionamento { Id = 122, GrupoId = 15, Minimo = 20, Maximo = 50, QtdaEfetivos = 1, QtdaSuplentes = 1 },
                new LinhaDimensionamento { Id = 123, GrupoId = 15, Minimo = 51, Maximo = 80, QtdaEfetivos = 2, QtdaSuplentes = 2 },
                new LinhaDimensionamento { Id = 124, GrupoId = 15, Minimo = 81, Maximo = 120, QtdaEfetivos = 3, QtdaSuplentes = 3 },
                new LinhaDimensionamento { Id = 125, GrupoId = 15, Minimo = 121, Maximo = 300, QtdaEfetivos = 4, QtdaSuplentes = 3 },
                new LinhaDimensionamento { Id = 126, GrupoId = 15, Minimo = 301, Maximo = 500, QtdaEfetivos = 5, QtdaSuplentes = 4 },
                new LinhaDimensionamento { Id = 127, GrupoId = 15, Minimo = 501, Maximo = 1000, QtdaEfetivos = 6, QtdaSuplentes = 4 },
                new LinhaDimensionamento { Id = 128, GrupoId = 15, Minimo = 1001, Maximo = 2500, QtdaEfetivos = 9, QtdaSuplentes = 7 },
                new LinhaDimensionamento { Id = 129, GrupoId = 15, Minimo = 2501, Maximo = 5000, QtdaEfetivos = 10, QtdaSuplentes = 8 },
                new LinhaDimensionamento { Id = 130, GrupoId = 15, Minimo = 5001, Maximo = 10000, QtdaEfetivos = 12, QtdaSuplentes = 10 },
                new LinhaDimensionamento { Id = 131, GrupoId = 16, Minimo = 0, Maximo = 19, QtdaEfetivos = 0, QtdaSuplentes = 0 },
                new LinhaDimensionamento { Id = 132, GrupoId = 16, Minimo = 20, Maximo = 50, QtdaEfetivos = 1, QtdaSuplentes = 1 },
                new LinhaDimensionamento { Id = 133, GrupoId = 16, Minimo = 51, Maximo = 80, QtdaEfetivos = 2, QtdaSuplentes = 2 },
                new LinhaDimensionamento { Id = 134, GrupoId = 16, Minimo = 81, Maximo = 120, QtdaEfetivos = 3, QtdaSuplentes = 3 },
                new LinhaDimensionamento { Id = 135, GrupoId = 16, Minimo = 121, Maximo = 300, QtdaEfetivos = 4, QtdaSuplentes = 3 },
                new LinhaDimensionamento { Id = 136, GrupoId = 16, Minimo = 301, Maximo = 500, QtdaEfetivos = 5, QtdaSuplentes = 4 },
                new LinhaDimensionamento { Id = 137, GrupoId = 16, Minimo = 501, Maximo = 1000, QtdaEfetivos = 7, QtdaSuplentes = 6 },
                new LinhaDimensionamento { Id = 138, GrupoId = 16, Minimo = 1001, Maximo = 2500, QtdaEfetivos = 8, QtdaSuplentes = 6 },
                new LinhaDimensionamento { Id = 139, GrupoId = 16, Minimo = 2501, Maximo = 5000, QtdaEfetivos = 9, QtdaSuplentes = 7 },
                new LinhaDimensionamento { Id = 140, GrupoId = 16, Minimo = 5001, Maximo = 10000, QtdaEfetivos = 10, QtdaSuplentes = 8 },
                new LinhaDimensionamento { Id = 141, GrupoId = 17, Minimo = 0, Maximo = 19, QtdaEfetivos = 0, QtdaSuplentes = 0 },
                new LinhaDimensionamento { Id = 142, GrupoId = 17, Minimo = 20, Maximo = 50, QtdaEfetivos = 1, QtdaSuplentes = 1 },
                new LinhaDimensionamento { Id = 143, GrupoId = 17, Minimo = 51, Maximo = 140, QtdaEfetivos = 3, QtdaSuplentes = 3 },
                new LinhaDimensionamento { Id = 144, GrupoId = 17, Minimo = 141, Maximo = 300, QtdaEfetivos = 4, QtdaSuplentes = 3 },
                new LinhaDimensionamento { Id = 145, GrupoId = 17, Minimo = 301, Maximo = 500, QtdaEfetivos = 5, QtdaSuplentes = 4 },
                new LinhaDimensionamento { Id = 146, GrupoId = 17, Minimo = 501, Maximo = 1000, QtdaEfetivos = 6, QtdaSuplentes = 5 },
                new LinhaDimensionamento { Id = 147, GrupoId = 17, Minimo = 1001, Maximo = 2500, QtdaEfetivos = 9, QtdaSuplentes = 7 },
                new LinhaDimensionamento { Id = 148, GrupoId = 17, Minimo = 2501, Maximo = 5000, QtdaEfetivos = 11, QtdaSuplentes = 8 },
                new LinhaDimensionamento { Id = 149, GrupoId = 17, Minimo = 5001, Maximo = 10000, QtdaEfetivos = 13, QtdaSuplentes = 10 },
                new LinhaDimensionamento { Id = 150, GrupoId = 18, Minimo = 0, Maximo = 19, QtdaEfetivos = 0, QtdaSuplentes = 0 },
                new LinhaDimensionamento { Id = 151, GrupoId = 18, Minimo = 20, Maximo = 50, QtdaEfetivos = 1, QtdaSuplentes = 1 },
                new LinhaDimensionamento { Id = 152, GrupoId = 18, Minimo = 51, Maximo = 100, QtdaEfetivos = 2, QtdaSuplentes = 2 },
                new LinhaDimensionamento { Id = 153, GrupoId = 18, Minimo = 101, Maximo = 120, QtdaEfetivos = 3, QtdaSuplentes = 3 },
                new LinhaDimensionamento { Id = 154, GrupoId = 18, Minimo = 121, Maximo = 140, QtdaEfetivos = 4, QtdaSuplentes = 3 },
                new LinhaDimensionamento { Id = 155, GrupoId = 18, Minimo = 141, Maximo = 300, QtdaEfetivos = 4, QtdaSuplentes = 4 },
                new LinhaDimensionamento { Id = 156, GrupoId = 18, Minimo = 301, Maximo = 500, QtdaEfetivos = 5, QtdaSuplentes = 4 },
                new LinhaDimensionamento { Id = 157, GrupoId = 18, Minimo = 501, Maximo = 1000, QtdaEfetivos = 6, QtdaSuplentes = 5 },
                new LinhaDimensionamento { Id = 158, GrupoId = 18, Minimo = 1001, Maximo = 2500, QtdaEfetivos = 9, QtdaSuplentes = 7 },
                new LinhaDimensionamento { Id = 159, GrupoId = 18, Minimo = 2501, Maximo = 10000, QtdaEfetivos = 11, QtdaSuplentes = 9 },
                new LinhaDimensionamento { Id = 160, GrupoId = 19, Minimo = 0, Maximo = 50, QtdaEfetivos = 0, QtdaSuplentes = 0 },
                new LinhaDimensionamento { Id = 161, GrupoId = 19, Minimo = 51, Maximo = 100, QtdaEfetivos = 1, QtdaSuplentes = 1 },
                new LinhaDimensionamento { Id = 162, GrupoId = 19, Minimo = 101, Maximo = 300, QtdaEfetivos = 2, QtdaSuplentes = 2 },
                new LinhaDimensionamento { Id = 163, GrupoId = 19, Minimo = 301, Maximo = 1000, QtdaEfetivos = 3, QtdaSuplentes = 3 },
                new LinhaDimensionamento { Id = 164, GrupoId = 19, Minimo = 1001, Maximo = 2500, QtdaEfetivos = 4, QtdaSuplentes = 3 },
                new LinhaDimensionamento { Id = 165, GrupoId = 19, Minimo = 2501, Maximo = 5000, QtdaEfetivos = 5, QtdaSuplentes = 4 },
                new LinhaDimensionamento { Id = 166, GrupoId = 19, Minimo = 5001, Maximo = 10000, QtdaEfetivos = 6, QtdaSuplentes = 4 },
                new LinhaDimensionamento { Id = 167, GrupoId = 20, Minimo = 0, Maximo = 19, QtdaEfetivos = 0, QtdaSuplentes = 0 },
                new LinhaDimensionamento { Id = 168, GrupoId = 20, Minimo = 20, Maximo = 50, QtdaEfetivos = 1, QtdaSuplentes = 1 },
                new LinhaDimensionamento { Id = 169, GrupoId = 20, Minimo = 51, Maximo = 100, QtdaEfetivos = 3, QtdaSuplentes = 3 },
                new LinhaDimensionamento { Id = 170, GrupoId = 20, Minimo = 101, Maximo = 300, QtdaEfetivos = 4, QtdaSuplentes = 3 },
                new LinhaDimensionamento { Id = 171, GrupoId = 20, Minimo = 301, Maximo = 500, QtdaEfetivos = 5, QtdaSuplentes = 4 },
                new LinhaDimensionamento { Id = 172, GrupoId = 20, Minimo = 501, Maximo = 1000, QtdaEfetivos = 6, QtdaSuplentes = 4 },
                new LinhaDimensionamento { Id = 173, GrupoId = 20, Minimo = 1001, Maximo = 2500, QtdaEfetivos = 8, QtdaSuplentes = 6 },
                new LinhaDimensionamento { Id = 174, GrupoId = 20, Minimo = 2501, Maximo = 5000, QtdaEfetivos = 10, QtdaSuplentes = 8 },
                new LinhaDimensionamento { Id = 175, GrupoId = 20, Minimo = 5001, Maximo = 10000, QtdaEfetivos = 12, QtdaSuplentes = 10 },
                new LinhaDimensionamento { Id = 176, GrupoId = 21, Minimo = 0, Maximo = 19, QtdaEfetivos = 0, QtdaSuplentes = 0 },
                new LinhaDimensionamento { Id = 177, GrupoId = 21, Minimo = 20, Maximo = 50, QtdaEfetivos = 1, QtdaSuplentes = 1 },
                new LinhaDimensionamento { Id = 178, GrupoId = 21, Minimo = 51, Maximo = 80, QtdaEfetivos = 2, QtdaSuplentes = 2 },
                new LinhaDimensionamento { Id = 179, GrupoId = 21, Minimo = 81, Maximo = 140, QtdaEfetivos = 3, QtdaSuplentes = 3 },
                new LinhaDimensionamento { Id = 180, GrupoId = 21, Minimo = 141, Maximo = 300, QtdaEfetivos = 4, QtdaSuplentes = 3 },
                new LinhaDimensionamento { Id = 181, GrupoId = 21, Minimo = 301, Maximo = 500, QtdaEfetivos = 5, QtdaSuplentes = 4 },
                new LinhaDimensionamento { Id = 182, GrupoId = 21, Minimo = 501, Maximo = 1000, QtdaEfetivos = 6, QtdaSuplentes = 4 },
                new LinhaDimensionamento { Id = 183, GrupoId = 21, Minimo = 1001, Maximo = 2500, QtdaEfetivos = 8, QtdaSuplentes = 6 },
                new LinhaDimensionamento { Id = 184, GrupoId = 21, Minimo = 2501, Maximo = 5000, QtdaEfetivos = 10, QtdaSuplentes = 7 },
                new LinhaDimensionamento { Id = 185, GrupoId = 21, Minimo = 5001, Maximo = 10000, QtdaEfetivos = 12, QtdaSuplentes = 9 },
                new LinhaDimensionamento { Id = 186, GrupoId = 22, Minimo = 0, Maximo = 19, QtdaEfetivos = 0, QtdaSuplentes = 0 },
                new LinhaDimensionamento { Id = 187, GrupoId = 22, Minimo = 20, Maximo = 50, QtdaEfetivos = 1, QtdaSuplentes = 1 },
                new LinhaDimensionamento { Id = 188, GrupoId = 22, Minimo = 51, Maximo = 100, QtdaEfetivos = 2, QtdaSuplentes = 2 },
                new LinhaDimensionamento { Id = 189, GrupoId = 22, Minimo = 101, Maximo = 300, QtdaEfetivos = 4, QtdaSuplentes = 3 },
                new LinhaDimensionamento { Id = 190, GrupoId = 22, Minimo = 301, Maximo = 500, QtdaEfetivos = 4, QtdaSuplentes = 4 },
                new LinhaDimensionamento { Id = 191, GrupoId = 22, Minimo = 501, Maximo = 1000, QtdaEfetivos = 6, QtdaSuplentes = 5 },
                new LinhaDimensionamento { Id = 192, GrupoId = 22, Minimo = 1001, Maximo = 2500, QtdaEfetivos = 8, QtdaSuplentes = 7 },
                new LinhaDimensionamento { Id = 193, GrupoId = 22, Minimo = 2501, Maximo = 5000, QtdaEfetivos = 10, QtdaSuplentes = 8 },
                new LinhaDimensionamento { Id = 194, GrupoId = 22, Minimo = 5001, Maximo = 10000, QtdaEfetivos = 12, QtdaSuplentes = 10 },
                new LinhaDimensionamento { Id = 195, GrupoId = 23, Minimo = 0, Maximo = 50, QtdaEfetivos = 0, QtdaSuplentes = 0 },
                new LinhaDimensionamento { Id = 196, GrupoId = 23, Minimo = 51, Maximo = 100, QtdaEfetivos = 2, QtdaSuplentes = 2 },
                new LinhaDimensionamento { Id = 197, GrupoId = 23, Minimo = 101, Maximo = 300, QtdaEfetivos = 4, QtdaSuplentes = 3 },
                new LinhaDimensionamento { Id = 198, GrupoId = 23, Minimo = 301, Maximo = 500, QtdaEfetivos = 4, QtdaSuplentes = 4 },
                new LinhaDimensionamento { Id = 199, GrupoId = 23, Minimo = 501, Maximo = 1000, QtdaEfetivos = 6, QtdaSuplentes = 5 },
                new LinhaDimensionamento { Id = 200, GrupoId = 23, Minimo = 1001, Maximo = 2500, QtdaEfetivos = 8, QtdaSuplentes = 7 },
                new LinhaDimensionamento { Id = 201, GrupoId = 23, Minimo = 2501, Maximo = 5000, QtdaEfetivos = 10, QtdaSuplentes = 8 },
                new LinhaDimensionamento { Id = 202, GrupoId = 23, Minimo = 5001, Maximo = 10000, QtdaEfetivos = 12, QtdaSuplentes = 10 },
                new LinhaDimensionamento { Id = 203, GrupoId = 24, Minimo = 0, Maximo = 50, QtdaEfetivos = 0, QtdaSuplentes = 0 },
                new LinhaDimensionamento { Id = 204, GrupoId = 24, Minimo = 51, Maximo = 100, QtdaEfetivos = 3, QtdaSuplentes = 3 },
                new LinhaDimensionamento { Id = 205, GrupoId = 24, Minimo = 101, Maximo = 300, QtdaEfetivos = 4, QtdaSuplentes = 3 },
                new LinhaDimensionamento { Id = 206, GrupoId = 24, Minimo = 301, Maximo = 500, QtdaEfetivos = 4, QtdaSuplentes = 4 },
                new LinhaDimensionamento { Id = 207, GrupoId = 24, Minimo = 501, Maximo = 1000, QtdaEfetivos = 6, QtdaSuplentes = 5 },
                new LinhaDimensionamento { Id = 208, GrupoId = 24, Minimo = 1001, Maximo = 2500, QtdaEfetivos = 9, QtdaSuplentes = 7 },
                new LinhaDimensionamento { Id = 209, GrupoId = 24, Minimo = 2501, Maximo = 5000, QtdaEfetivos = 12, QtdaSuplentes = 9 },
                new LinhaDimensionamento { Id = 210, GrupoId = 24, Minimo = 5001, Maximo = 10000, QtdaEfetivos = 15, QtdaSuplentes = 12 },
                new LinhaDimensionamento { Id = 211, GrupoId = 25, Minimo = 0, Maximo = 50, QtdaEfetivos = 0, QtdaSuplentes = 0 },
                new LinhaDimensionamento { Id = 212, GrupoId = 25, Minimo = 51, Maximo = 100, QtdaEfetivos = 1, QtdaSuplentes = 1 },
                new LinhaDimensionamento { Id = 213, GrupoId = 25, Minimo = 101, Maximo = 300, QtdaEfetivos = 2, QtdaSuplentes = 2 },
                new LinhaDimensionamento { Id = 214, GrupoId = 25, Minimo = 301, Maximo = 1000, QtdaEfetivos = 3, QtdaSuplentes = 3 },
                new LinhaDimensionamento { Id = 215, GrupoId = 25, Minimo = 1001, Maximo = 2500, QtdaEfetivos = 4, QtdaSuplentes = 3 },
                new LinhaDimensionamento { Id = 216, GrupoId = 25, Minimo = 2501, Maximo = 5000, QtdaEfetivos = 5, QtdaSuplentes = 4 },
                new LinhaDimensionamento { Id = 217, GrupoId = 25, Minimo = 5001, Maximo = 10000, QtdaEfetivos = 6, QtdaSuplentes = 4 },
                new LinhaDimensionamento { Id = 218, GrupoId = 26, Minimo = 0, Maximo = 29, QtdaEfetivos = 0, QtdaSuplentes = 0 },
                new LinhaDimensionamento { Id = 219, GrupoId = 26, Minimo = 30, Maximo = 80, QtdaEfetivos = 1, QtdaSuplentes = 1 },
                new LinhaDimensionamento { Id = 220, GrupoId = 26, Minimo = 81, Maximo = 300, QtdaEfetivos = 3, QtdaSuplentes = 3 },
                new LinhaDimensionamento { Id = 221, GrupoId = 26, Minimo = 301, Maximo = 500, QtdaEfetivos = 4, QtdaSuplentes = 3 },
                new LinhaDimensionamento { Id = 222, GrupoId = 26, Minimo = 501, Maximo = 2500, QtdaEfetivos = 5, QtdaSuplentes = 4 },
                new LinhaDimensionamento { Id = 223, GrupoId = 26, Minimo = 2501, Maximo = 5000, QtdaEfetivos = 6, QtdaSuplentes = 5 },
                new LinhaDimensionamento { Id = 224, GrupoId = 26, Minimo = 5001, Maximo = 10000, QtdaEfetivos = 8, QtdaSuplentes = 6 },
                new LinhaDimensionamento { Id = 225, GrupoId = 27, Minimo = 0, Maximo = 50, QtdaEfetivos = 0, QtdaSuplentes = 0 },
                new LinhaDimensionamento { Id = 226, GrupoId = 27, Minimo = 51, Maximo = 100, QtdaEfetivos = 1, QtdaSuplentes = 1 },
                new LinhaDimensionamento { Id = 227, GrupoId = 27, Minimo = 101, Maximo = 300, QtdaEfetivos = 2, QtdaSuplentes = 2 },
                new LinhaDimensionamento { Id = 228, GrupoId = 27, Minimo = 301, Maximo = 1000, QtdaEfetivos = 3, QtdaSuplentes = 3 },
                new LinhaDimensionamento { Id = 229, GrupoId = 27, Minimo = 1001, Maximo = 2500, QtdaEfetivos = 4, QtdaSuplentes = 3 },
                new LinhaDimensionamento { Id = 230, GrupoId = 27, Minimo = 2501, Maximo = 5000, QtdaEfetivos = 5, QtdaSuplentes = 4 },
                new LinhaDimensionamento { Id = 231, GrupoId = 27, Minimo = 5001, Maximo = 10000, QtdaEfetivos = 6, QtdaSuplentes = 5 },
                new LinhaDimensionamento { Id = 232, GrupoId = 28, Minimo = 0, Maximo = 19, QtdaEfetivos = 0, QtdaSuplentes = 0 },
                new LinhaDimensionamento { Id = 233, GrupoId = 28, Minimo = 20, Maximo = 50, QtdaEfetivos = 1, QtdaSuplentes = 1 },
                new LinhaDimensionamento { Id = 234, GrupoId = 28, Minimo = 51, Maximo = 100, QtdaEfetivos = 2, QtdaSuplentes = 2 },
                new LinhaDimensionamento { Id = 235, GrupoId = 28, Minimo = 101, Maximo = 140, QtdaEfetivos = 3, QtdaSuplentes = 3 },
                new LinhaDimensionamento { Id = 236, GrupoId = 28, Minimo = 141, Maximo = 500, QtdaEfetivos = 4, QtdaSuplentes = 3 },
                new LinhaDimensionamento { Id = 237, GrupoId = 28, Minimo = 501, Maximo = 1000, QtdaEfetivos = 6, QtdaSuplentes = 5 },
                new LinhaDimensionamento { Id = 238, GrupoId = 28, Minimo = 1001, Maximo = 2500, QtdaEfetivos = 8, QtdaSuplentes = 6 },
                new LinhaDimensionamento { Id = 239, GrupoId = 28, Minimo = 2501, Maximo = 5000, QtdaEfetivos = 10, QtdaSuplentes = 8 },
                new LinhaDimensionamento { Id = 240, GrupoId = 28, Minimo = 5001, Maximo = 10000, QtdaEfetivos = 12, QtdaSuplentes = 9 },
                new LinhaDimensionamento { Id = 241, GrupoId = 29, Minimo = 0, Maximo = 50, QtdaEfetivos = 0, QtdaSuplentes = 0 },
                new LinhaDimensionamento { Id = 242, GrupoId = 29, Minimo = 51, Maximo = 100, QtdaEfetivos = 1, QtdaSuplentes = 1 },
                new LinhaDimensionamento { Id = 243, GrupoId = 29, Minimo = 101, Maximo = 500, QtdaEfetivos = 2, QtdaSuplentes = 2 },
                new LinhaDimensionamento { Id = 244, GrupoId = 29, Minimo = 501, Maximo = 1000, QtdaEfetivos = 3, QtdaSuplentes = 3 },
                new LinhaDimensionamento { Id = 245, GrupoId = 29, Minimo = 1001, Maximo = 2500, QtdaEfetivos = 4, QtdaSuplentes = 3 },
                new LinhaDimensionamento { Id = 246, GrupoId = 29, Minimo = 2501, Maximo = 5000, QtdaEfetivos = 5, QtdaSuplentes = 4 },
                new LinhaDimensionamento { Id = 247, GrupoId = 29, Minimo = 5001, Maximo = 10000, QtdaEfetivos = 6, QtdaSuplentes = 5 },
                new LinhaDimensionamento { Id = 248, GrupoId = 30, Minimo = 0, Maximo = 19, QtdaEfetivos = 0, QtdaSuplentes = 0 },
                new LinhaDimensionamento { Id = 249, GrupoId = 30, Minimo = 20, Maximo = 50, QtdaEfetivos = 1, QtdaSuplentes = 1 },
                new LinhaDimensionamento { Id = 250, GrupoId = 30, Minimo = 51, Maximo = 100, QtdaEfetivos = 2, QtdaSuplentes = 2 },
                new LinhaDimensionamento { Id = 251, GrupoId = 30, Minimo = 101, Maximo = 140, QtdaEfetivos = 4, QtdaSuplentes = 3 },
                new LinhaDimensionamento { Id = 252, GrupoId = 30, Minimo = 141, Maximo = 500, QtdaEfetivos = 4, QtdaSuplentes = 4 },
                new LinhaDimensionamento { Id = 253, GrupoId = 30, Minimo = 501, Maximo = 1000, QtdaEfetivos = 6, QtdaSuplentes = 5 },
                new LinhaDimensionamento { Id = 254, GrupoId = 30, Minimo = 1001, Maximo = 2500, QtdaEfetivos = 8, QtdaSuplentes = 7 },
                new LinhaDimensionamento { Id = 255, GrupoId = 30, Minimo = 2501, Maximo = 5000, QtdaEfetivos = 10, QtdaSuplentes = 8 },
                new LinhaDimensionamento { Id = 256, GrupoId = 30, Minimo = 5001, Maximo = 10000, QtdaEfetivos = 12, QtdaSuplentes = 10 },
                new LinhaDimensionamento { Id = 257, GrupoId = 31, Minimo = 0, Maximo = 50, QtdaEfetivos = 0, QtdaSuplentes = 0 },
                new LinhaDimensionamento { Id = 258, GrupoId = 31, Minimo = 51, Maximo = 100, QtdaEfetivos = 1, QtdaSuplentes = 1 },
                new LinhaDimensionamento { Id = 259, GrupoId = 31, Minimo = 101, Maximo = 500, QtdaEfetivos = 2, QtdaSuplentes = 2 },
                new LinhaDimensionamento { Id = 260, GrupoId = 31, Minimo = 501, Maximo = 1000, QtdaEfetivos = 3, QtdaSuplentes = 3 },
                new LinhaDimensionamento { Id = 261, GrupoId = 31, Minimo = 1001, Maximo = 2500, QtdaEfetivos = 4, QtdaSuplentes = 3 },
                new LinhaDimensionamento { Id = 262, GrupoId = 31, Minimo = 2501, Maximo = 5000, QtdaEfetivos = 5, QtdaSuplentes = 4 },
                new LinhaDimensionamento { Id = 263, GrupoId = 31, Minimo = 5001, Maximo = 10000, QtdaEfetivos = 6, QtdaSuplentes = 4 },
                new LinhaDimensionamento { Id = 264, GrupoId = 32, Minimo = 0, Maximo = 19, QtdaEfetivos = 0, QtdaSuplentes = 0 },
                new LinhaDimensionamento { Id = 265, GrupoId = 32, Minimo = 20, Maximo = 50, QtdaEfetivos = 1, QtdaSuplentes = 1 },
                new LinhaDimensionamento { Id = 266, GrupoId = 32, Minimo = 51, Maximo = 100, QtdaEfetivos = 3, QtdaSuplentes = 3 },
                new LinhaDimensionamento { Id = 267, GrupoId = 32, Minimo = 101, Maximo = 500, QtdaEfetivos = 4, QtdaSuplentes = 3 },
                new LinhaDimensionamento { Id = 268, GrupoId = 32, Minimo = 501, Maximo = 1000, QtdaEfetivos = 6, QtdaSuplentes = 4 },
                new LinhaDimensionamento { Id = 269, GrupoId = 32, Minimo = 1001, Maximo = 2500, QtdaEfetivos = 9, QtdaSuplentes = 7 },
                new LinhaDimensionamento { Id = 270, GrupoId = 32, Minimo = 2501, Maximo = 5000, QtdaEfetivos = 12, QtdaSuplentes = 9 },
                new LinhaDimensionamento { Id = 271, GrupoId = 32, Minimo = 5001, Maximo = 10000, QtdaEfetivos = 15, QtdaSuplentes = 12 },
                new LinhaDimensionamento { Id = 272, GrupoId = 33, Minimo = 0, Maximo = 50, QtdaEfetivos = 0, QtdaSuplentes = 0 },
                new LinhaDimensionamento { Id = 273, GrupoId = 33, Minimo = 51, Maximo = 100, QtdaEfetivos = 1, QtdaSuplentes = 1 },
                new LinhaDimensionamento { Id = 274, GrupoId = 33, Minimo = 101, Maximo = 140, QtdaEfetivos = 2, QtdaSuplentes = 1 },
                new LinhaDimensionamento { Id = 275, GrupoId = 33, Minimo = 141, Maximo = 500, QtdaEfetivos = 2, QtdaSuplentes = 2 },
                new LinhaDimensionamento { Id = 276, GrupoId = 33, Minimo = 501, Maximo = 1000, QtdaEfetivos = 4, QtdaSuplentes = 4 },
                new LinhaDimensionamento { Id = 277, GrupoId = 33, Minimo = 1001, Maximo = 2500, QtdaEfetivos = 5, QtdaSuplentes = 5 },
                new LinhaDimensionamento { Id = 278, GrupoId = 33, Minimo = 2501, Maximo = 10000, QtdaEfetivos = 7, QtdaSuplentes = 7 },
                new LinhaDimensionamento { Id = 279, GrupoId = 34, Minimo = 0, Maximo = 50, QtdaEfetivos = 0, QtdaSuplentes = 0 },
                new LinhaDimensionamento { Id = 280, GrupoId = 34, Minimo = 51, Maximo = 100, QtdaEfetivos = 1, QtdaSuplentes = 1 },
                new LinhaDimensionamento { Id = 281, GrupoId = 34, Minimo = 101, Maximo = 140, QtdaEfetivos = 2, QtdaSuplentes = 1 },
                new LinhaDimensionamento { Id = 282, GrupoId = 34, Minimo = 141, Maximo = 300, QtdaEfetivos = 2, QtdaSuplentes = 2 },
                new LinhaDimensionamento { Id = 283, GrupoId = 34, Minimo = 301, Maximo = 500, QtdaEfetivos = 3, QtdaSuplentes = 2 },
                new LinhaDimensionamento { Id = 284, GrupoId = 34, Minimo = 501, Maximo = 1000, QtdaEfetivos = 4, QtdaSuplentes = 4 },
                new LinhaDimensionamento { Id = 285, GrupoId = 34, Minimo = 1001, Maximo = 2500, QtdaEfetivos = 5, QtdaSuplentes = 5 },
                new LinhaDimensionamento { Id = 286, GrupoId = 34, Minimo = 2501, Maximo = 5000, QtdaEfetivos = 7, QtdaSuplentes = 7 },
                new LinhaDimensionamento { Id = 287, GrupoId = 34, Minimo = 5001, Maximo = 10000, QtdaEfetivos = 9, QtdaSuplentes = 9 },
                new LinhaDimensionamento { Id = 288, GrupoId = 35, Minimo = 0, Maximo = 50, QtdaEfetivos = 0, QtdaSuplentes = 0 },
                new LinhaDimensionamento { Id = 289, GrupoId = 35, Minimo = 51, Maximo = 100, QtdaEfetivos = 1, QtdaSuplentes = 1 },
                new LinhaDimensionamento { Id = 290, GrupoId = 35, Minimo = 101, Maximo = 500, QtdaEfetivos = 2, QtdaSuplentes = 2 },
                new LinhaDimensionamento { Id = 291, GrupoId = 35, Minimo = 501, Maximo = 1000, QtdaEfetivos = 3, QtdaSuplentes = 3 },
                new LinhaDimensionamento { Id = 292, GrupoId = 35, Minimo = 1001, Maximo = 2500, QtdaEfetivos = 4, QtdaSuplentes = 3 },
                new LinhaDimensionamento { Id = 293, GrupoId = 35, Minimo = 2501, Maximo = 5000, QtdaEfetivos = 5, QtdaSuplentes = 4 },
                new LinhaDimensionamento { Id = 294, GrupoId = 35, Minimo = 5001, Maximo = 10000, QtdaEfetivos = 6, QtdaSuplentes = 5 },
                new LinhaDimensionamento { Id = 295, GrupoId = 36, Minimo = 0, Maximo = 300, QtdaEfetivos = 0, QtdaSuplentes = 0 },
                new LinhaDimensionamento { Id = 296, GrupoId = 36, Minimo = 301, Maximo = 500, QtdaEfetivos = 1, QtdaSuplentes = 1 },
                new LinhaDimensionamento { Id = 297, GrupoId = 36, Minimo = 501, Maximo = 1000, QtdaEfetivos = 2, QtdaSuplentes = 2 },
                new LinhaDimensionamento { Id = 298, GrupoId = 36, Minimo = 1001, Maximo = 2500, QtdaEfetivos = 3, QtdaSuplentes = 3 },
                new LinhaDimensionamento { Id = 299, GrupoId = 36, Minimo = 2501, Maximo = 5000, QtdaEfetivos = 4, QtdaSuplentes = 3 },
                new LinhaDimensionamento { Id = 300, GrupoId = 36, Minimo = 5001, Maximo = 10000, QtdaEfetivos = 5, QtdaSuplentes = 4 },
                new LinhaDimensionamento { Id = 301, GrupoId = 37, Minimo = 0, Maximo = 100, QtdaEfetivos = 0, QtdaSuplentes = 0 },
                new LinhaDimensionamento { Id = 302, GrupoId = 37, Minimo = 101, Maximo = 140, QtdaEfetivos = 1, QtdaSuplentes = 1 },
                new LinhaDimensionamento { Id = 303, GrupoId = 37, Minimo = 141, Maximo = 300, QtdaEfetivos = 2, QtdaSuplentes = 2 },
                new LinhaDimensionamento { Id = 304, GrupoId = 37, Minimo = 301, Maximo = 500, QtdaEfetivos = 3, QtdaSuplentes = 3 },
                new LinhaDimensionamento { Id = 305, GrupoId = 37, Minimo = 501, Maximo = 1000, QtdaEfetivos = 4, QtdaSuplentes = 3 },
                new LinhaDimensionamento { Id = 306, GrupoId = 37, Minimo = 1001, Maximo = 2500, QtdaEfetivos = 5, QtdaSuplentes = 4 },
                new LinhaDimensionamento { Id = 307, GrupoId = 37, Minimo = 2501, Maximo = 10000, QtdaEfetivos = 6, QtdaSuplentes = 5 },
                new LinhaDimensionamento { Id = 308, GrupoId = 38, Minimo = 0, Maximo = 100, QtdaEfetivos = 0, QtdaSuplentes = 0 },
                new LinhaDimensionamento { Id = 309, GrupoId = 38, Minimo = 101, Maximo = 140, QtdaEfetivos = 1, QtdaSuplentes = 1 },
                new LinhaDimensionamento { Id = 310, GrupoId = 38, Minimo = 141, Maximo = 300, QtdaEfetivos = 2, QtdaSuplentes = 2 },
                new LinhaDimensionamento { Id = 311, GrupoId = 38, Minimo = 301, Maximo = 500, QtdaEfetivos = 3, QtdaSuplentes = 3 },
                new LinhaDimensionamento { Id = 312, GrupoId = 38, Minimo = 501, Maximo = 1000, QtdaEfetivos = 4, QtdaSuplentes = 4 },
                new LinhaDimensionamento { Id = 313, GrupoId = 38, Minimo = 1001, Maximo = 2500, QtdaEfetivos = 5, QtdaSuplentes = 5 },
                new LinhaDimensionamento { Id = 314, GrupoId = 38, Minimo = 2501, Maximo = 10000, QtdaEfetivos = 6, QtdaSuplentes = 5 },
                new LinhaDimensionamento { Id = 315, GrupoId = 39, Minimo = 0, Maximo = 300, QtdaEfetivos = 0, QtdaSuplentes = 0 },
                new LinhaDimensionamento { Id = 316, GrupoId = 39, Minimo = 301, Maximo = 500, QtdaEfetivos = 1, QtdaSuplentes = 1 },
                new LinhaDimensionamento { Id = 317, GrupoId = 39, Minimo = 501, Maximo = 1000, QtdaEfetivos = 2, QtdaSuplentes = 2 },
                new LinhaDimensionamento { Id = 318, GrupoId = 39, Minimo = 1001, Maximo = 2500, QtdaEfetivos = 3, QtdaSuplentes = 3 },
                new LinhaDimensionamento { Id = 319, GrupoId = 39, Minimo = 2501, Maximo = 5000, QtdaEfetivos = 4, QtdaSuplentes = 3 },
                new LinhaDimensionamento { Id = 320, GrupoId = 39, Minimo = 5001, Maximo = 10000, QtdaEfetivos = 5, QtdaSuplentes = 4 },
                new LinhaDimensionamento { Id = 321, GrupoId = 40, Minimo = 0, Maximo = 19, QtdaEfetivos = 0, QtdaSuplentes = 0 },
                new LinhaDimensionamento { Id = 322, GrupoId = 40, Minimo = 20, Maximo = 80, QtdaEfetivos = 1, QtdaSuplentes = 1 },
                new LinhaDimensionamento { Id = 323, GrupoId = 40, Minimo = 81, Maximo = 100, QtdaEfetivos = 2, QtdaSuplentes = 2 },
                new LinhaDimensionamento { Id = 324, GrupoId = 40, Minimo = 101, Maximo = 140, QtdaEfetivos = 4, QtdaSuplentes = 3 },
                new LinhaDimensionamento { Id = 325, GrupoId = 40, Minimo = 141, Maximo = 300, QtdaEfetivos = 4, QtdaSuplentes = 4 },
                new LinhaDimensionamento { Id = 326, GrupoId = 40, Minimo = 301, Maximo = 500, QtdaEfetivos = 5, QtdaSuplentes = 4 },
                new LinhaDimensionamento { Id = 327, GrupoId = 40, Minimo = 501, Maximo = 1000, QtdaEfetivos = 7, QtdaSuplentes = 6 },
                new LinhaDimensionamento { Id = 328, GrupoId = 40, Minimo = 1001, Maximo = 2500, QtdaEfetivos = 8, QtdaSuplentes = 7 },
                new LinhaDimensionamento { Id = 329, GrupoId = 40, Minimo = 2501, Maximo = 5000, QtdaEfetivos = 9, QtdaSuplentes = 8 },
                new LinhaDimensionamento { Id = 330, GrupoId = 40, Minimo = 5001, Maximo = 10000, QtdaEfetivos = 10, QtdaSuplentes = 9 },
                new LinhaDimensionamento { Id = 331, GrupoId = 41, Minimo = 0, Maximo = 50, QtdaEfetivos = 0, QtdaSuplentes = 0 },
                new LinhaDimensionamento { Id = 332, GrupoId = 41, Minimo = 51, Maximo = 100, QtdaEfetivos = 1, QtdaSuplentes = 1 },
                new LinhaDimensionamento { Id = 333, GrupoId = 41, Minimo = 101, Maximo = 300, QtdaEfetivos = 2, QtdaSuplentes = 2 },
                new LinhaDimensionamento { Id = 334, GrupoId = 41, Minimo = 301, Maximo = 1000, QtdaEfetivos = 3, QtdaSuplentes = 3 },
                new LinhaDimensionamento { Id = 335, GrupoId = 41, Minimo = 1001, Maximo = 2500, QtdaEfetivos = 4, QtdaSuplentes = 3 },
                new LinhaDimensionamento { Id = 336, GrupoId = 41, Minimo = 2501, Maximo = 5000, QtdaEfetivos = 5, QtdaSuplentes = 4 },
                new LinhaDimensionamento { Id = 337, GrupoId = 41, Minimo = 5001, Maximo = 10000, QtdaEfetivos = 6, QtdaSuplentes = 5 },
                new LinhaDimensionamento { Id = 338, GrupoId = 42, Minimo = 0, Maximo = 50, QtdaEfetivos = 0, QtdaSuplentes = 0 },
                new LinhaDimensionamento { Id = 339, GrupoId = 42, Minimo = 51, Maximo = 100, QtdaEfetivos = 1, QtdaSuplentes = 1 },
                new LinhaDimensionamento { Id = 340, GrupoId = 42, Minimo = 101, Maximo = 300, QtdaEfetivos = 2, QtdaSuplentes = 2 },
                new LinhaDimensionamento { Id = 341, GrupoId = 42, Minimo = 301, Maximo = 1000, QtdaEfetivos = 3, QtdaSuplentes = 3 },
                new LinhaDimensionamento { Id = 342, GrupoId = 42, Minimo = 1001, Maximo = 2500, QtdaEfetivos = 4, QtdaSuplentes = 3 },
                new LinhaDimensionamento { Id = 343, GrupoId = 42, Minimo = 2501, Maximo = 5000, QtdaEfetivos = 5, QtdaSuplentes = 4 },
                new LinhaDimensionamento { Id = 344, GrupoId = 42, Minimo = 5001, Maximo = 10000, QtdaEfetivos = 6, QtdaSuplentes = 5 },
                new LinhaDimensionamento { Id = 345, GrupoId = 43, Minimo = 0, Maximo = 100, QtdaEfetivos = 0, QtdaSuplentes = 0 },
                new LinhaDimensionamento { Id = 346, GrupoId = 43, Minimo = 101, Maximo = 500, QtdaEfetivos = 1, QtdaSuplentes = 1 },
                new LinhaDimensionamento { Id = 347, GrupoId = 43, Minimo = 501, Maximo = 1000, QtdaEfetivos = 2, QtdaSuplentes = 2 },
                new LinhaDimensionamento { Id = 348, GrupoId = 43, Minimo = 1001, Maximo = 2500, QtdaEfetivos = 3, QtdaSuplentes = 3 },
                new LinhaDimensionamento { Id = 349, GrupoId = 43, Minimo = 2501, Maximo = 5000, QtdaEfetivos = 4, QtdaSuplentes = 3 },
                new LinhaDimensionamento { Id = 350, GrupoId = 43, Minimo = 5001, Maximo = 10000, QtdaEfetivos = 5, QtdaSuplentes = 4 },
                new LinhaDimensionamento { Id = 351, GrupoId = 44, Minimo = 0, Maximo = 19, QtdaEfetivos = 0, QtdaSuplentes = 0 },
                new LinhaDimensionamento { Id = 352, GrupoId = 44, Minimo = 20, Maximo = 50, QtdaEfetivos = 1, QtdaSuplentes = 1 },
                new LinhaDimensionamento { Id = 353, GrupoId = 44, Minimo = 51, Maximo = 100, QtdaEfetivos = 2, QtdaSuplentes = 2 },
                new LinhaDimensionamento { Id = 354, GrupoId = 44, Minimo = 101, Maximo = 300, QtdaEfetivos = 4, QtdaSuplentes = 3 },
                new LinhaDimensionamento { Id = 355, GrupoId = 44, Minimo = 301, Maximo = 500, QtdaEfetivos = 4, QtdaSuplentes = 4 },
                new LinhaDimensionamento { Id = 356, GrupoId = 44, Minimo = 501, Maximo = 1000, QtdaEfetivos = 6, QtdaSuplentes = 5 },
                new LinhaDimensionamento { Id = 357, GrupoId = 44, Minimo = 1001, Maximo = 2500, QtdaEfetivos = 8, QtdaSuplentes = 7 },
                new LinhaDimensionamento { Id = 358, GrupoId = 44, Minimo = 2501, Maximo = 5000, QtdaEfetivos = 10, QtdaSuplentes = 8 },
                new LinhaDimensionamento { Id = 359, GrupoId = 44, Minimo = 5001, Maximo = 10000, QtdaEfetivos = 12, QtdaSuplentes = 9 },
                new LinhaDimensionamento { Id = 360, GrupoId = 45, Minimo = 0, Maximo = 50, QtdaEfetivos = 0, QtdaSuplentes = 0 },
                new LinhaDimensionamento { Id = 361, GrupoId = 45, Minimo = 51, Maximo = 100, QtdaEfetivos = 1, QtdaSuplentes = 1 },
                new LinhaDimensionamento { Id = 362, GrupoId = 45, Minimo = 101, Maximo = 500, QtdaEfetivos = 2, QtdaSuplentes = 2 },
                new LinhaDimensionamento { Id = 363, GrupoId = 45, Minimo = 501, Maximo = 1000, QtdaEfetivos = 3, QtdaSuplentes = 3 },
                new LinhaDimensionamento { Id = 364, GrupoId = 45, Minimo = 1001, Maximo = 2500, QtdaEfetivos = 4, QtdaSuplentes = 3 },
                new LinhaDimensionamento { Id = 365, GrupoId = 45, Minimo = 2501, Maximo = 5000, QtdaEfetivos = 5, QtdaSuplentes = 4 },
                new LinhaDimensionamento { Id = 366, GrupoId = 45, Minimo = 5001, Maximo = 10000, QtdaEfetivos = 6, QtdaSuplentes = 5 }
            };

            Usuario usuario = new Usuario
            {
                Id = 1,
                Email = "teste@email.com",
                Nome = "Teste",
                Senha = "03c32dc379d1b0958f3ef87d94ebb4ec859b9e2fdd297f44d68d8dd5f36800cc",// Teste12
                Perfil = Perfil.SESMT,
                ContaId = 1,
                DataCadastro = new DateTime(2019, 1, 1)
            };

            Empresa empresa = new Empresa
            {
                Id = 1,
                Cnpj = "01540533000390",
                Ativa = true,
                ContaId = 1,
                RazaoSocial = "Empresa Teste",
                DataCadastro = new DateTime(2019, 1, 1)
            };

            Estabelecimento estabelecimento = new Estabelecimento
            {
                Id = 1,
                Ativo = true,
                Cidade = "Uberlândia",
                Descricao = "Teste",
                EmpresaId = 1,
                Endereco = "Teste",
                GrupoId = 1,
                DataCadastro = new DateTime(2019, 1, 1)
            };

            var etapasObrigatorias = new EtapaObrigatoria[6] {
                new EtapaObrigatoria
                {
                    Id = CodigoEtapaObrigatoria.Convocacao,
                    Nome = "Convocação para a Eleição",
                    Descricao = "No início do processo eleitoral, o empregador deve convocar as eleições para a escolha dos representantes dos empregados na CIPA. Essa convocação precisa ocorrer no prazo mínimo de 60 dias antes do término do mandato em curso (NR-05 - 5.38)",
                    Ordem = (int)CodigoEtapaObrigatoria.Convocacao,
                    PrazoMandatoAnterior = 60
                },
                new EtapaObrigatoria
                {
                    Id = CodigoEtapaObrigatoria.FormacaoComissao,
                    Nome = "Formação da Comissão Eleitoral",
                    Descricao = "A Norma Regulamentadora 05 também determina que, no prazo mínimo de 55 dias antes do término do mandato em curso, seja constituída a Comissão Eleitoral (CE). Essa comissão deve ser formada pelos membros atuais da CIPA e será responsável pela organização e acompanhamento do processo eleitoral (NR-05 5.39). O edital de convocação também deve ser enviado para o sindicatos 5 dias após sua publicação.",
                    Ordem = (int)CodigoEtapaObrigatoria.FormacaoComissao,
                    PrazoMandatoAnterior = 55
                },
                new EtapaObrigatoria
                {
                    Id = CodigoEtapaObrigatoria.EditalInscricao,
                    Nome = "Edital de Inscrição dos Candidatos",
                    Descricao = "Nessa etapa, é preciso publicar e divulgar o edital de inscrição para a CIPA, em locais de fácil acesso e visualização. Atente-se ao prazo! A NR-5 determina que a publicação ocorra no prazo mínimo de 45 dias antes do término do mandato em curso. (NR-05 - 5.40 a)",
                    Ordem = (int)CodigoEtapaObrigatoria.EditalInscricao,
                    PrazoMandatoAnterior = 45
                },
                new EtapaObrigatoria
                {
                    Id = CodigoEtapaObrigatoria.Inscricao,
                    Nome = "Inscrição dos Candidatos",
                    Descricao = "Nessa etapa, o sistema libera acesso aos eleitores cadastrados nessa eleição para eles realizarem sua inscrição. Essa etapa deve ter duração mínima de 15 dias. É importante lembrar que qualquer empregado do estabelecimento, independentemente do setor ou local de trabalho, pode se inscrever. (NR-05 5.40 b. c.)",
                    DuracaoMinima = 15,
                    Ordem = (int)CodigoEtapaObrigatoria.Inscricao
                },
                new EtapaObrigatoria
                {
                    Id = CodigoEtapaObrigatoria.Votacao,
                    Nome = "Votação",
                    Descricao = "Nessa etapa, todos os eleitores podem acessar o sistema e escolher um dos candidatos como representante para o próximo mandato da CIPA. A eleição deve ser realizada em um dia normal de trabalho e 30 dias antes do término do mandato em curso, no mínimo. (NR-05 5.40 e. f.)",
                    Ordem = (int)CodigoEtapaObrigatoria.Votacao,
                    PrazoMandatoAnterior = 30
                },
                new EtapaObrigatoria
                {
                    Id = CodigoEtapaObrigatoria.Ata,
                    Nome = "Ata de Eleição",
                    Descricao = "Os candidatos votados e não eleitos devem estar relacionados nessa ata, em ordem decrescente de votos para nomeação posterior, em caso de vacância de suplentes. Não se preocupe, a criação desse documento é por nossa conta!",
                    Ordem = (int)CodigoEtapaObrigatoria.Ata
                }
            };

            var etapasPadroesConta = new EtapaPadraoConta[6];
            for (var i = 0; i < 6; i++)
            {
                etapasPadroesConta[i] = new EtapaPadraoConta
                {
                    Id = (int)etapasObrigatorias[i].Id,
                    ContaId = 1,
                    Descricao = etapasObrigatorias[i].Descricao,
                    DuracaoPadrao = 5,
                    EtapaObrigatoriaId = etapasObrigatorias[i].Id,
                    Nome = etapasObrigatorias[i].Nome,
                    Ordem = etapasObrigatorias[i].Ordem
                };
            }

            modelBuilder.Entity<Conta>().HasData(conta);
            modelBuilder.Entity<Empresa>().HasData(empresa);
            modelBuilder.Entity<Grupo>().HasData(grupos);
            modelBuilder.Entity<LimiteDimensionamento>().HasData(limitesDimensionamentos);
            modelBuilder.Entity<LinhaDimensionamento>().HasData(linhaDimensionamentos);
            modelBuilder.Entity<Usuario>().HasData(usuario);
            modelBuilder.Entity<Estabelecimento>().HasData(estabelecimento);
            modelBuilder.Entity<EtapaObrigatoria>().HasData(etapasObrigatorias);
            modelBuilder.Entity<EtapaPadraoConta>().HasData(etapasPadroesConta);
        }
    }
}
